abort if not tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,21 +18,25 @@ jobs:
 
       - run: echo "hi from release"
 
-      - name: Download ci info
+      - name: Download ci artifact
         uses: dawidd6/action-download-artifact@v2
         with:
           workflow: ${{ github.event.workflow_run.workflow_id }}
           name: ci-info
           path: ci-info
           repo: wipfli/tags-for-actions
-      
-      - name: Read ref
-        id: read_ref
-        run: |
-          Ref=$(cat ci-info/github-ref)
-          echo "Ref is $Ref"
-          echo "::set-output name=ref::$Ref"
+    
+      - name: Read ci-info/github-ref
+        id: ref
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./ci-info/github-ref
 
-      - name: Is tag
-        if: startsWith(steps.read_ref.outputs.ref, 'refs/tags/')
-        run: is tag
+      - name: CI GitHub ref is not a tag, abort
+        if: ! startsWith(steps.ref.outputs.content, 'refs/tags/')
+        run: |
+          echo "CI GitHub ref is not a tag, abort"
+          exit 1
+      
+      - name: Continue
+        run: echo "continue release"
